### ISSUE TITLE
Is Firebug 3 Development dead?

### ISSUE THREAD

**Issue by TheLaGmAn** [firebug/firebug.next#405]
Its been MONTHS since i reported 3 issues, all reproducible and other users as well and no one looks into them and are very important issues to my opinion.

Is the development halted or something?

The last update was from  23-Apr-2015
After that, nothing, and two days ago a new update was released with typo fixes on comments.
Looks to me like no one is working on this, after almost 4 months of no releases.

Any idea on how will this continue? Firebug is one of the best tools for development in my opinion, it as a shame to see how its stopping on updates.

**Comment by janodvarko** [comment]
The simple answer is no.

But you are right, the focus has been recently more on moving some features to the platform and less on Firebug.next itself. This has changed and you should see more regular releases again. As you said, the latest was two days ago and it wasn't just typo fixes (one of the main changes was e.g. that the DOM panel works on e10s).

Anyways, I'll make sure to update the discussion group with notes about the progress, so the community knows what's happening and what the plans are.

Honza

**Comment by SeanKendle** [comment]
I’m guessing you haven’t been paying attention, then, because there has
been a lot of development going on.



Maybe you don’t realize this is being done by one man, for free.







*From:* TheLaGmAn [mailto:notifications@github.com]
*Sent:* Tuesday, August 11, 2015 8:40 PM
*To:* firebug/firebug.next <firebug.next@noreply.github.com>
*Subject:* [firebug.next] Is Firebug 3 Development dead? (#405)



Its been MONTHS since i reported 3 issues, all reproducible and other users
as well and no one looks into them and are very important issues to my
opinion.

Is the development halted or something?

The last update was from 23-Apr-2015
After that, nothing, and two days ago a new update was released with typo
fixes on comments.
Looks to me like no one is working on this, after almost 4 months of no
releases.

Any idea on how will this continue? Firebug is one of the best tools for
development in my opinion, it as a shame to see how its stopping on updates.

—
Reply to this email directly or view it on GitHub
<https://github.com/firebug/firebug.next/issues/405>.

**Comment by janodvarko** [comment]
> Maybe you don’t realize this is being done by one man, for free.

I don't know who are you talking about, but I am personally backed by Mozilla ;-)

Honza

**Comment by SeanKendle** [comment]
Oh, well then, cheers for that!  Haha!



But, what I meant was the plugin is free.







*From:* Jan Odvarko [mailto:notifications@github.com]
*Sent:* Wednesday, August 12, 2015 11:28 AM
*To:* firebug/firebug.next <firebug.next@noreply.github.com>
*Cc:* SeanKendle <sdk@joyceinc.com>
*Subject:* Re: [firebug.next] Is Firebug 3 Development dead? (#405)



Maybe you don’t realize this is being done by one man, for free.

I don't know who are you talking about, but I am personally backed by
Mozilla ;-)

Honza

—
Reply to this email directly or view it on GitHub
<https://github.com/firebug/firebug.next/issues/405#issuecomment-130342531>.

**Comment by TheLaGmAn** [comment]
Thanks Jan, thats what i wanted to hear, i really appreciate the effort you put into it, its an awesome debug tool :)

Could you please take a look at my 3 issues when you get a chance? Let me know if you need more info on them.
