### ISSUE TITLE
Broken layout on OS X

### ISSUE THREAD

**Issue by SebastianZ** [firebug/firebug.next#471]
According to a [discussion group thread](https://groups.google.com/d/topic/firebug/zhDpCvNbhFA/discussion), Firebug 3 beta 3 breaks the DevTools UI on OS X El Capitan in Firefox 46.0.1.
There it looks like this:
![Broken layout on OS X El Capitan using Firefox 46.0.1](https://15398002529664494918.googlegroups.com/attach/604c1c5f30773/firebug3%20freshInstall.jpg?part=0.1&view=1&vt=ANaJVrGkKCsBsUYbQ6_Dm-eYonJniEBVN-HaIJFivg_nL466odGh8gGyYpVwdOcNdvvEApNwMwKntoVSrS-Xtq7HdPf9Nnj7gQDzhwU2g3HEdXKxSGCVodA)

Sebastian

**Comment by aolin480** [comment]
and I just confirmed that everything is good in Firefox Nightly, so it seems strapped to version 46, and 46.0.1. I first noticed it on 46, then again on 46.0.1

**Comment by SebastianZ** [comment]
Thanks for the info! So obviously 46.0 has changed something that breaks Firebug.

Sebastian

**Comment by aolin480** [comment]
I feel like an idiot, but I have Firebug 3.0 working with 46.0.1, the only issue is, I needed to restart Firefox a couple of times, and the layout is now good and in working order. So there may be something up with the "No Restart" feature?

**Comment by SebastianZ** [comment]
> I needed to restart Firefox a couple of times, and the layout is now good and in working order. So there may be something up with the "No Restart" feature?

Could be. Though I installed it right now on a fresh Firefox profile on my Windows 10 and it worked as expected directly after installing it. I also tried to install it while the devtools were open and detached and didn't see any issues.

So, it's either something that only happens on OS X or a conflict with another extension or some setting in your profile.

I close this issue for now. If you find out some reproducible steps, we can reopen it.

Sebastian

**Comment by aolin480** [comment]
I went ahead and waited patiently for Firefox 47 to come out, because this is still an issue on my machine. I know I said it was fixed, but after more use, it was back to the same again and I just thought I would wait till 47 came out, so I uninstalled firefox on my Mac, and installed ONLY Firebug 3.0 and Firefox 47, but the issue was still there. I made sure I deleted my Firefox profile on the filesystem as well. I don't know why it works well in Nightly, but regular Firefox, with no profile, the layout is still broken. You can see the screenshots attached.

![snip20160607_8](https://cloud.githubusercontent.com/assets/1616101/15882423/fe1c6580-2d03-11e6-8a18-876dd72b7368.png)
![snip20160607_1](https://cloud.githubusercontent.com/assets/1616101/15882424/fe21fa86-2d03-11e6-9aaf-2ce9cf30d5ab.png)
